language: java
os: linux
install: true
jdk: openjdk8
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: andreag93
    token:
      secure: DoRqBrGIM5r16mfHsfYIIlA2T7bWPioSRAyiyE3tqftJ3uBk4uTT4s/tVJaxDT/vaZtLRUyM3tEpGyZcYs5dZu3AP0sGuDQi4BXbsrZc5R6a3U3qbvDPgAfNjV8hV1Wt9lkf2DJqpiEktL6AJBqX1U0K6gYA8dldU7WJvEWQDvgZUWPJ1K4HvBkY9Vi/r8NjACBAZrSP+LDiDAo55tNdEx9Wp/+dDQURe0tmmliIm66Sp0lFLJFldx0Rqi/oihIsAlzq51nm1MfptELNwsNPclnNCHcwDRSko8Xui1rmrbCX4HHIBKuIUHDfU8Xl8/OkyL3BTLKjIsIsggaRaoAGCVMiR228cAcBzKs9vWPsIQjhBV5So5TGlpj+3Ci5A9s2AYDLXOIjUVb6dYk9fLCJD3r4/lKMRIrn1pPFCf5pjrOyGC8AySzsNuFY7tconl0oZjoJa41cMxo7gks427APMapwEiiap7yiurfxymtQZZTEW5Ssm1aS/KAJqn+GaCCup7CgLUWXbkC1xhGrHqVadx9F5ALtHrfwp7XHzAi4qNgAu6KHsQKGbIw9x8qt4w7mlD9Ok+PiBgwVVsJ2xnNPBMZMRozn2xf7Mx9y2aZlf6YhpIJw/wufysmAA5u8m3ygPTIZYNckOebLBxh079i2/eWa6rXHXnY+Ii/aw2FOUco=

script:
- mvn clean verify sonar:sonar -Dsonar.projectKey=AndreaG93_ISW2-bookkeeper    
